# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run tests.py

services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=[access_key_id]"
  secret_access_key:
    secure: "Encypted <secret-access-key>=[secret_access_key]"
  region: "[region]"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "[bucket_name]"

# Push the results back to codecov
after_success:
  - codecov